name: lint check

on: pull_request

jobs:
  eslint-test:
    name: eslint test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.7.0'
      - run: npm install
      - run: npm run lint